# Generated by Django 3.1.2 on 2021-06-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payhistory',
            name='paystack_access_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='payhistory',
            name='paystack_charge_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
