# Generated by Django 3.1.2 on 2021-06-21 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210616_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='profile_pic',
        ),
        migrations.AlterField(
            model_name='plan',
            name='plan_type',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Premium', 'Premium'), ('Standard', 'Standard'), ('Free', 'Free')], default='Free', max_length=30),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='UpdateProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='')),
                ('id_card', models.FileField(default='', upload_to='documents/%Y/%m/%d')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
