# Generated by Django 3.1.2 on 2021-03-30 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userregistration_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='properties',
        ),
    ]
