# Generated by Django 3.1.2 on 2021-06-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210621_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='id_card',
            field=models.FileField(default='', upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='userregistration',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
