# Generated by Django 3.1.2 on 2021-06-28 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_payhistory_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userplan',
            name='reference_code',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='userplan',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_plan', to='accounts.plan'),
        ),
    ]
