# Generated by Django 3.1.2 on 2021-04-13 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.IntegerField(default=0)),
                ('duration', models.CharField(max_length=20, verbose_name='duration')),
                ('images', models.CharField(max_length=20, verbose_name='images')),
                ('amount', models.FloatField(default=0)),
                ('listings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.IntegerField(default=0)),
                ('duration', models.CharField(max_length=20, verbose_name='duration')),
                ('images', models.CharField(max_length=20, verbose_name='images')),
                ('amount', models.FloatField(default=0)),
                ('listings', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured', models.IntegerField(default=0)),
                ('duration', models.CharField(max_length=20, verbose_name='duration')),
                ('images', models.CharField(max_length=20, verbose_name='images')),
                ('amount', models.FloatField(default=0)),
                ('listings', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='plan',
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_gold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_standard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gold',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gold', to='accounts.gold'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='premium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='premium', to='accounts.premium'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='standard',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standard', to='accounts.standard'),
        ),
    ]
