# Generated by Django 3.1.2 on 2021-06-29 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210628_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='id_card',
        ),
        migrations.RemoveField(
            model_name='userregistration',
            name='profile_pic',
        ),
    ]
