# Generated by Django 3.1.2 on 2021-06-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210621_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='whatsapp_phone_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='id_card',
            field=models.FileField(blank=True, default='', null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
