# Generated by Django 3.1.2 on 2021-04-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210413_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='gold',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='name_gold'),
        ),
        migrations.AddField(
            model_name='premium',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='name_premium'),
        ),
        migrations.AddField(
            model_name='standard',
            name='name',
            field=models.CharField(default='', max_length=20, verbose_name='name_standard'),
        ),
    ]
