# Generated by Django 3.1.2 on 2021-06-29 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210629_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='updateprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.updateprofile'),
        ),
        migrations.AlterField(
            model_name='updateprofile',
            name='profile_pic',
            field=models.ImageField(default='assets/img/avatar.png', upload_to='profile_pics/'),
        ),
    ]
