# Generated by Django 3.1.2 on 2021-07-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20210629_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
