# Generated by Django 3.1.2 on 2021-03-29 20:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='featured_title')),
                ('status', models.CharField(max_length=20, verbose_name='featured_status')),
                ('types', models.CharField(max_length=20, verbose_name='featured_types')),
                ('price', models.IntegerField(default=0)),
                ('area', models.CharField(max_length=20, verbose_name='featured_area')),
                ('bedrooms', models.CharField(max_length=20, verbose_name='featured_bedrooms')),
                ('bathrooms', models.CharField(max_length=20, verbose_name='featured_bathrooms')),
                ('image_one', models.ImageField(default='', upload_to='property/')),
                ('image_two', models.ImageField(default='', upload_to='property/')),
                ('image_three', models.ImageField(default='', upload_to='property/')),
                ('image_four', models.ImageField(default='', upload_to='property/')),
                ('image_five', models.ImageField(default='', upload_to='property/')),
                ('location', models.CharField(max_length=20, verbose_name='featured_location')),
                ('description', models.TextField(max_length=50, verbose_name='featured_description')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('status', models.CharField(max_length=20, verbose_name='status')),
                ('types', models.CharField(max_length=20, verbose_name='types')),
                ('price', models.IntegerField(default=0)),
                ('area', models.CharField(max_length=20, verbose_name='area')),
                ('bedrooms', models.CharField(max_length=20, verbose_name='bedrooms')),
                ('bathrooms', models.CharField(max_length=20, verbose_name='bathrooms')),
                ('image_one', models.ImageField(default='', upload_to='property/')),
                ('image_two', models.ImageField(default='', upload_to='property/')),
                ('image_three', models.ImageField(default='', upload_to='property/')),
                ('image_four', models.ImageField(default='', upload_to='property/')),
                ('image_five', models.ImageField(default='', upload_to='property/')),
                ('location', models.CharField(max_length=20, verbose_name='location')),
                ('description', models.TextField(max_length=50, verbose_name='description')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
