# Generated by Django 3.1.2 on 2021-06-22 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('status', models.CharField(max_length=20, verbose_name='status')),
                ('types', models.CharField(max_length=20, verbose_name='types')),
                ('price', models.IntegerField(default=0)),
                ('slug', models.SlugField(default='property', max_length=200)),
                ('area', models.CharField(max_length=20, verbose_name='area')),
                ('bedrooms', models.CharField(max_length=20, verbose_name='bedrooms')),
                ('bathrooms', models.CharField(max_length=20, verbose_name='bathrooms')),
                ('image_one', models.ImageField(default='', upload_to='property/')),
                ('image_two', models.ImageField(blank=True, default='', null=True, upload_to='property/')),
                ('image_three', models.ImageField(blank=True, default='', null=True, upload_to='property/')),
                ('image_four', models.ImageField(blank=True, default='', null=True, upload_to='property/')),
                ('image_five', models.ImageField(blank=True, default='', null=True, upload_to='property/')),
                ('location', models.CharField(max_length=200, verbose_name='location')),
                ('description', models.TextField(max_length=2000, verbose_name='description')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='featured_title')),
                ('status', models.CharField(max_length=20, verbose_name='featured_status')),
                ('types', models.CharField(max_length=20, verbose_name='featured_types')),
                ('price', models.IntegerField(default=0)),
                ('slug', models.SlugField(default='property', max_length=200)),
                ('area', models.CharField(max_length=20, verbose_name='featured_area')),
                ('bedrooms', models.CharField(max_length=20, verbose_name='featured_bedrooms')),
                ('bathrooms', models.CharField(max_length=20, verbose_name='featured_bathrooms')),
                ('image_one', models.ImageField(default='', upload_to='property/')),
                ('image_two', models.ImageField(default='', upload_to='property/')),
                ('image_three', models.ImageField(default='', upload_to='property/')),
                ('image_four', models.ImageField(default='', upload_to='property/')),
                ('image_five', models.ImageField(default='', upload_to='property/')),
                ('location', models.CharField(max_length=20, verbose_name='featured_location')),
                ('description', models.TextField(max_length=50, verbose_name='featured_description')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
