# Generated by Django 3.1.2 on 2021-07-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproperty',
            name='area',
            field=models.CharField(max_length=100, verbose_name='featured_area'),
        ),
        migrations.AlterField(
            model_name='featuredproperty',
            name='description',
            field=models.TextField(max_length=100, verbose_name='featured_description'),
        ),
        migrations.AlterField(
            model_name='featuredproperty',
            name='location',
            field=models.CharField(max_length=100, verbose_name='featured_location'),
        ),
        migrations.AlterField(
            model_name='featuredproperty',
            name='status',
            field=models.CharField(max_length=100, verbose_name='featured_status'),
        ),
        migrations.AlterField(
            model_name='featuredproperty',
            name='title',
            field=models.CharField(max_length=100, verbose_name='featured_title'),
        ),
        migrations.AlterField(
            model_name='featuredproperty',
            name='types',
            field=models.CharField(max_length=100, verbose_name='featured_types'),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
