# Generated by Django 3.1.2 on 2021-07-23 15:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20210722_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproperty',
            name='image_five',
            field=cloudinary.models.CloudinaryField(blank='true', max_length=255, null='true'),
        ),
        migrations.AlterField(
            model_name='featuredproperty',
            name='image_four',
            field=cloudinary.models.CloudinaryField(blank='true', max_length=255, null='true'),
        ),
        migrations.AlterField(
            model_name='featuredproperty',
            name='image_one',
            field=cloudinary.models.CloudinaryField(blank='true', max_length=255, null='true'),
        ),
        migrations.AlterField(
            model_name='featuredproperty',
            name='image_three',
            field=cloudinary.models.CloudinaryField(blank='true', max_length=255, null='true'),
        ),
        migrations.AlterField(
            model_name='featuredproperty',
            name='image_two',
            field=cloudinary.models.CloudinaryField(blank='true', max_length=255, null='true'),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_five',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_four',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_one',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_three',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='image_two',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True),
        ),
    ]
