# Generated by Django 3.1.2 on 2021-03-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20210330_1518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='properties',
            new_name='customer',
        ),
    ]
