# Generated by Django 3.1.2 on 2021-04-08 21:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('properties', '0004_auto_20210408_1623'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredproperty',
            options={'ordering': ['-created_on']},
        ),
        migrations.AddField(
            model_name='featuredproperty',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
